### ISSUE TITLE
Missing dash-html-components/dash_html_components/metadata.json file in repo

### ISSUE THREAD

**Issue by bkelemen56** [plotly/dash-html-components#26]
I'm testing the **dash-display-error-messages.py** demo file from **dash-recipes** repo and get this error message:
```
IOError: [Errno 2] No such file or directory: '/Users/xxxxxxxx/GitHub/dash-html-components/dash_html_components/metadata.json'
```

This file is not included in the dash-html-components repo so not sure what's happening.

I've cloned the following repos onto my local machine (/Users/xxxxxxxx/GitHub/):
- dash
- dash-core-components
- dash-html-components
- dash-renderer
- dash-recipes

Stacktrace:
```
Traceback (most recent call last):
  File "/Users/xxxxxxxx/GitHub/dash-recipes/dash-display-error-messages.py", line 4, in <module>
    import dash_html_components as html
  File "/Users/xxxxxxxx/GitHub/dash-html-components/dash_html_components/__init__.py", line 13, in <module>
    'dash_html_components'
  File "/Users/xxxxxxxx/GitHub/dash/dash/development/component_loader.py", line 24, in load_components
    with open(metadata_path) as data_file:
IOError: [Errno 2] No such file or directory: '/Users/xxxxxxxx/GitHub/dash-html-components/dash_html_components/metadata.json'
```

These are my installed packages in the venv taken from requirements.txt of the dash repo (excluding other dash packages):
```
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
certifi==2016.2.28
click==6.7
decorator==4.0.11
enum34==1.1.6
Flask==0.12
Flask-Compress==1.4.0
Flask-SeaSurf==0.2.2
funcsigs==1.0.2
functools32==3.2.3.post2
ipdb==0.10.2
ipython==5.3.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.9.5
jsonschema==2.6.0
jupyter-core==4.3.0
MarkupSafe==1.0
mock==2.0.0
nbformat==4.3.0
numpy==1.11.0
pathlib2==2.2.1
pbr==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
plotly==2.0.8
pluggy==0.4.0
prompt-toolkit==1.0.14
ptyprocess==0.5.1
py==1.4.33
Pygments==2.2.0
python-dateutil==2.5.3
pytz==2017.2
requests==2.13.0
requests-file==1.4.1
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
tox==2.7.0
traitlets==4.3.2
virtualenv==15.1.0
wcwidth==0.1.7
Werkzeug==0.12.1
```

**Comment by chriddyp** [comment]
@bkelemen56 - To install this library, you should use pip:
```
pip install dash-html-components
```

This library includes some "build" files that are kept out of source control and are generated when creating a package. If you want to create those build files yourself, you can run
```
npm install
npm run prepublish
```

**Comment by bkelemen56** [comment]
Thanks Chris. I tried to build dash-html-components with the commands you suggested:
```
npm install
npm run prepublish
```
and get this error:
```
> builder run lint

[builder:config:environment] {"cwd":"/Users/williamkelemen/GitHub/dash-html-components","dir":"/Users/williamkelemen/GitHub/dash-html-components/node_modules/builder/lib"}
[builder:builder-core:start:50835] Started: run lint
[builder:run] lint - eslint --fix --ignore-path .gitignore .
[builder:proc:start] Command: eslint --fix --ignore-path .gitignore .

/Users/williamkelemen/GitHub/dash-html-components/src/components/Nextid: the next id element (obsolete).react.js
  4:13  error  Parsing error: Unexpected token :

/Users/williamkelemen/GitHub/dash-html-components/src/index.js
  82:14  error  Parsing error: Unexpected token :

✖ 2 problems (2 errors, 0 warnings)

[builder:proc:end:1] Command: eslint --fix --ignore-path .gitignore .
[builder:builder-core:end:50835] Task: run lint, Error: Command failed: sh -c eslint --fix --ignore-path .gitignore .

npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-html-components@0.8.0 prepublish: `npm run clean && npm run generate-components && npm test && ./node_modules/.bin/builder run build-dist && npm run copy-lib`
npm ERR! Exit status 1
npm ERR! 
```
I noticed this error in the generated `src\index.js`:
```
import Nextid: the next id element (obsolete) from './components/Nextid: the next id element (obsolete).react';
```
and traced it down to this line in `data/elements.txt`:
```
nextid: the next id element (obsolete)
```
Not sure if it can safely removed to rebuild.

**Comment by chriddyp** [comment]
So the install scripts actually scrape MDN to generate the metadata.json files. The MDN pages change frequently, so sometimes this scraping process needs to be refined or modified.

In this case, it looks like it's picking up some weird `Nextid` component from somewhere. What you can try is to add `Nextid` to the list of ignored elements here: https://github.com/plotly/dash-html-components/blob/6d04a70f098bb8640545467255ae382e8e17cffb/scripts/extract-elements.js#L15 and see if that fixes it. 

Otherwise, you can just run a few of the prepublish commands from https://github.com/plotly/dash-html-components/blob/6d04a70f098bb8640545467255ae382e8e17cffb/package.json#L22 like:

```
./node_modules/.bin/builder run build-dist && npm run copy-lib
```
